### ISSUE TITLE
audition.yaml file persists all actions in a folder

### ISSUE THREAD

**Issue by charneykaye** [go-audition/audition#2]
In any target folder, an **audition.yaml** file persists all the actions.

e.g. an **audition.yaml** for a folder with some .mp3 files that have been rated

```
--
files:
- name: song-a.mp3
  rating: 3
- name: song-b.mp3
  rating: 4
```
